# Travis continuous integration for Kitodo.Contentserver

dist: trusty

language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    packages:
      - ant-optional
      - tomcat7-common

cache:

env:

script: ant -lib /usr/share/tomcat7/lib all
